Repository ros2/rcl, pull requests merged in 2018-12, with the labels that each got.

#348 add rcl_action_server_is_valid_except_context
  rcl_action/include/rcl_action/action_server.h
  rcl_action/src/rcl_action/action_server.c
Labels: in review

#351 Enable test_action_communication to compile against available rmw
  rcl_action/CMakeLists.txt
Labels: in progress

#352 Adds action interaction tests
  rcl_action/CMakeLists.txt
  rcl_action/test/rcl_action/test_action_communication.cpp
  rcl_action/test/rcl_action/test_action_interaction.cpp
Labels: in progress

#333 Add node graph api to rcl
  rcl/include/rcl/graph.h
  rcl/src/rcl/graph.c
  rcl/test/CMakeLists.txt
  rcl/test/cmake/rcl_add_custom_gtest.cmake
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_guard_condition.cpp
Labels: in review

#353 Adapt to action implicit field changes
  rcl_action/test/rcl_action/test_action_communication.cpp
  rcl_action/test/rcl_action/test_action_interaction.cpp
Labels: in review

#327 Adding new cli parameters for configuring the logging.
  rcl/CMakeLists.txt
  rcl/cmake/get_default_rcl_logging_implementation.cmake
  rcl/include/rcl/arguments.h
  rcl/include/rcl/logging.h
  rcl/include/rcl/logging_external_interface.h
  rcl/include/rcl/macros.h
  rcl/package.xml
  rcl/src/rcl/arguments.c
  rcl/src/rcl/arguments_impl.h
  rcl/src/rcl/init.c
  rcl/src/rcl/logging.c
Labels: in review

#349 add wait_for_action_server() for action clients
  rcl_action/include/rcl_action/action_client.h
  rcl_action/src/rcl_action/action_client.c
Labels: enhancement, in review

#357 Set rmw_wait timeout using ros timers too
  rcl/src/rcl/wait.c
Labels: bug, in review

#359 Avoid timer period being set to 0
  rcl_action/src/rcl_action/action_server.c
Labels: bug, in review

#360 Fix logic that moves goal handles when one expires
  rcl_action/src/rcl_action/action_server.c
Labels: bug, in review

#364 Fix error from uncrustify v0.68
  rcl/src/rcl/rmw_implementation_identifier_check.c
Labels: in review
