Repository ros2/rcl, pull requests merged in 2018-03, with the labels that each got.

#215 update style
  rcl/src/rcl/client.c
  rcl/src/rcl/publisher.c
  rcl/src/rcl/service.c
  rcl/src/rcl/subscription.c
  rcl/test/memory_tools/test_memory_tools.cpp
Labels: in review

#218 Fix small leak of ns_with_separators in rcl_create_node_logger_name
  rcl/src/rcl/node.c
Labels: in review

#220 Add rcl_validate_topic_name_with_size()
  rcl/include/rcl/validate_topic_name.h
  rcl/src/rcl/validate_topic_name.c
Labels: in review

#217 Command line static remapping (ROS1 compatible syntax + nodename prefix)
  rcl/CMakeLists.txt
  rcl/include/rcl/arguments.h
  rcl/include/rcl/node.h
  rcl/include/rcl/remap.h
  rcl/include/rcl/types.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/arguments_impl.h
  rcl/src/rcl/client.c
  rcl/src/rcl/node.c
  rcl/src/rcl/publisher.c
  rcl/src/rcl/rcl.c
  rcl/src/rcl/remap.c
  rcl/src/rcl/remap_impl.h
  rcl/src/rcl/service.c
  rcl/src/rcl/subscription.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/arg_macros.hpp
  rcl/test/rcl/test_arguments.cpp
  rcl/test/rcl/test_remap.cpp
  rcl/test/rcl/test_remap_integration.cpp
Labels: in review

#222 Fix docs
  rcl/include/rcl/client.h
  rcl/include/rcl/node.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/service.h
  rcl/include/rcl/subscription.h
  rcl/src/rcl/client.c
Labels: documentation, in review

#221 CLI remapping followup
  rcl/include/rcl/arguments.h
  rcl/include/rcl/graph.h
  rcl/src/rcl/arguments.c
  rcl/test/rcl/test_arguments.cpp
Labels: in review

#216 change export order for static linking
  rcl/CMakeLists.txt
  rcl_lifecycle/CMakeLists.txt
Labels: in review

#223 Remove ros arguments
  rcl/include/rcl/arguments.h
  rcl/include/rcl/rcl.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/rcl.c
  rcl/test/rcl/test_arguments.cpp
Labels: in progress

#214 update doc for rmw_get_node_names to mention potential null values
  rcl/include/rcl/graph.h
Labels: in review
