Repository ros2/rcl, pull requests merged in 2018-08, with the labels that each got.

#275 Set error message when clock type is not ROS_TIME
  rcl/src/rcl/time.c
Labels: in review

#277 initialize memory before sending a message
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
Labels: bug, in review

#278 Deallocate ret_val to avoid memery leak
  rcl_yaml_param_parser/src/parser.c
Labels: in review

#283 ROS clock storage initially set to zero
  rcl/src/rcl/time.c
  rcl/test/rcl/test_time.cpp
Labels: bug, in review

#285 consolidate wait set functions
  rcl/include/rcl/wait.h
  rcl/src/rcl/wait.c
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl/test/rcl/test_wait.cpp
Labels: enhancement, in review

#284 Clock has multiple time jump callbacks
  rcl/include/rcl/time.h
  rcl/src/rcl/time.c
  rcl/test/rcl/test_time.cpp
Labels: enhancement, in review

#290 Check if pointers are null before calling memset
  rcl/src/rcl/wait.c
Labels: bug, in review
