Repository ros2/rcl, pull requests merged in 2018-09, with the labels that each got.

#288 Doc fixups
  rcl/include/rcl/arguments.h
  rcl/include/rcl/remap.h
  rcl_yaml_param_parser/include/rcl_yaml_param_parser/parser.h
Labels: in review

#292 fix naming of configure_error transition
  rcl_lifecycle/src/default_state_machine.c
Labels: bug, in review

#287 Include namespaces in get_node_names
  rcl/include/rcl/graph.h
  rcl/src/rcl/graph.c
  rcl/test/rcl/test_get_node_names.cpp
Labels: in progress

#294 Null deallocated jump callbacks
  rcl/src/rcl/time.c
  rcl/test/rcl/test_time.cpp
Labels: bug, in review

#291 fix calculation of next timer call
  rcl/src/rcl/timer.c
Labels: bug, in review

#295 ensure that timer period is non-negative
  rcl/include/rcl/timer.h
  rcl/src/rcl/timer.c
Labels: enhancement, in review

#297 typo
  rcl/include/rcl/node.h
Labels: in review

#286 Rcl timer with ros time
  rcl/include/rcl/timer.h
  rcl/src/rcl/timer.c
  rcl/src/rcl/wait.c
  rcl/test/rcl/test_timer.cpp
Labels: enhancement, in review

#299 [yaml parser] Fix FQN=//node_name when ns is /
  rcl_yaml_param_parser/src/parser.c
  rcl_yaml_param_parser/test/root_ns.yaml
  rcl_yaml_param_parser/test/test_parse_yaml.cpp
Labels: in review
