Repository ros2/rcl, pull requests merged in 2018-06, with the labels that each got.

#248 Print warning if non-FQN namespace remapping passed
  rcl/include/rcl/lexer.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/lexer_lookahead.c
Labels: in review

#250 migrate launch -> launch.legacy
  rcl/test/rcl/test_rmw_impl_id_check.py.in
  rcl/test/rcl/test_two_executables.py.in
Labels: in review

#253 Support passing yaml parameter files via commandline
  rcl/include/rcl/arguments.h
  rcl/include/rcl/types.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/arguments_impl.h
  rcl/test/rcl/test_arguments.cpp
Labels: in review

#238 update to use new memory_tools from osrf_testing_tools_cpp
  rcl/package.xml
  rcl/test/CMakeLists.txt
  rcl/test/memory_tools/CMakeLists.txt
  rcl/test/memory_tools/memory_tools.cpp
  rcl/test/memory_tools/memory_tools.hpp
  rcl/test/memory_tools/memory_tools_common.cpp
  rcl/test/memory_tools/memory_tools_osx_interpose.cpp
  rcl/test/memory_tools/test_memory_tools.cpp
  rcl/test/rcl/arg_macros.hpp
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/failing_allocator_functions.hpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_client.cpp
  rcl/test/rcl/test_get_node_names.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_guard_condition.cpp
  rcl/test/rcl/test_lexer_lookahead.cpp
  rcl/test/rcl/test_node.cpp
  rcl/test/rcl/test_publisher.cpp
  rcl/test/rcl/test_rcl.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl/test/rcl/test_time.cpp
  rcl/test/rcl/test_timer.cpp
  rcl/test/rcl/test_wait.cpp
  rcl/test/scope_exit.hpp
  rcl/test/test_namespace.cpp
Labels: enhancement, in progress

#256 Set default logger level from command line
  rcl/Doxyfile
  rcl/include/rcl/arguments.h
  rcl/include/rcl/types.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/arguments_impl.h
  rcl/src/rcl/rcl.c
  rcl/test/rcl/test_arguments.cpp
Labels: in review

#259 use test_msgs instead of example_interfaces
  rcl/package.xml
  rcl/test/CMakeLists.txt
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_client.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_remap_integration.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/test_namespace.cpp
Labels: in review

#170 *_raw function
  rcl/include/rcl/publisher.h
  rcl/include/rcl/subscription.h
  rcl/include/rcl/types.h
  rcl/src/rcl/publisher.c
  rcl/src/rcl/subscription.c
Labels: in progress

#240 use rcutils_format_string() rather than malloc and rcutils_snprintf()
  rcl/test/rcl/test_rcl.cpp
Labels: enhancement, in review

#260 Use private substitution in lifecycle topics and services
  rcl_lifecycle/src/com_interface.c
Labels: enhancement, in review

#261 changes to support memory audit
  rcl/src/rcl/node.c
  rcl/test/rcl/test_time.cpp
  rcl_yaml_param_parser/test/test_parse_yaml.cpp
Labels: enhancement, in review
