Repository ros2/rcl, pull requests merged in 2018-11, with the labels that each got.

#313 delete TRANSITION_SHUTDOWN
  rcl_lifecycle/test/test_default_state_machine.cpp
Labels: in review

#317 Add action services and topics name getters
  rcl_action/CMakeLists.txt
  rcl_action/include/rcl_action/names.h
  rcl_action/src/rcl_action/names.c
  rcl_action/test/rcl_action/test_names.cpp
Labels: in review

#322 Add subfolder argument to the ROSIDL_GET_SRV_TYPE_SUPPORT macro
  rcl/include/rcl/client.h
  rcl/include/rcl/service.h
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_client.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_remap_integration.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/test_namespace.cpp
Labels: in review

#324 Move stdatomic helper to rcutils
  rcl/src/rcl/client.c
  rcl/src/rcl/rcl.c
  rcl/src/rcl/stdatomic_helper.h
  rcl/src/rcl/stdatomic_helper/gcc/stdatomic.h
  rcl/src/rcl/stdatomic_helper/win32/stdatomic.h
  rcl/src/rcl/time.c
  rcl/src/rcl/timer.c
  rcl/src/rcl/wait.c
Labels: enhancement, in review

#325 [rcl_action] Add function to check if goal can be transitioned to CANCELING
  rcl_action/include/rcl_action/goal_handle.h
  rcl_action/src/rcl_action/goal_handle.c
  rcl_action/test/rcl_action/test_goal_handle.cpp
Labels: in review

#300 Expand node_secure_root using local_namespace
  rcl/src/rcl/node.c
Labels: in review

#319 Action client implementation
  rcl_action/CMakeLists.txt
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/types.h
  rcl_action/include/rcl_action/wait.h
  rcl_action/package.xml
  rcl_action/src/rcl_action/action_client.c
  rcl_action/test/rcl_action/test_action_client.cpp
Labels: in review

#329 Makes rcl_action_get_*_name() functions check for empty action names.
  rcl_action/include/rcl_action/names.h
  rcl_action/src/rcl_action/names.c
  rcl_action/test/rcl_action/test_names.cpp
Labels: bug, in review

#323 Action server implementation
  rcl_action/CMakeLists.txt
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/goal_handle.h
  rcl_action/include/rcl_action/types.h
  rcl_action/package.xml
  rcl_action/src/rcl_action/action_server.c
  rcl_action/src/rcl_action/goal_handle.c
  rcl_action/src/rcl_action/types.c
  rcl_action/test/rcl_action/test_action_communication.cpp
  rcl_action/test/rcl_action/test_action_server.cpp
  rcl_action/test/rcl_action/test_names.cpp
Labels: in review

#339 Exposes sequence numbers for all requests and responses
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/src/rcl_action/action_client.c
  rcl_action/src/rcl_action/action_server.c
  rcl_action/test/rcl_action/test_action_communication.cpp
Labels: in progress

#341 rcl_action_process_cancel_request no longer changes goal state
  rcl_action/include/rcl_action/action_server.h
  rcl_action/src/rcl_action/action_server.c
Labels: in review

#326 Methods to retrieve matched counts on pub/sub.
  rcl/include/rcl/publisher.h
  rcl/include/rcl/subscription.h
  rcl/src/rcl/publisher.c
  rcl/src/rcl/subscription.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_count_matched.cpp
Labels: in review

#342 rcl_action_expire_goals() outputs goals that expire
  rcl_action/include/rcl_action/action_server.h
  rcl_action/src/rcl_action/action_server.c
  rcl_action/test/rcl_action/test_action_server.cpp
Labels: in review

#331 Completes integration tests for action client/server
  rcl_action/src/rcl_action/action_client.c
  rcl_action/test/rcl_action/test_action_communication.cpp
Labels: in progress

#336 refactor init to not be global
  rcl/CMakeLists.txt
  rcl/include/rcl/arguments.h
  rcl/include/rcl/context.h
  rcl/include/rcl/guard_condition.h
  rcl/include/rcl/init.h
  rcl/include/rcl/init_options.h
  rcl/include/rcl/node.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/rcl.h
  rcl/include/rcl/timer.h
  rcl/include/rcl/types.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/client.c
  rcl/src/rcl/context.c
  rcl/src/rcl/context_impl.h
  rcl/src/rcl/graph.c
  rcl/src/rcl/guard_condition.c
  rcl/src/rcl/init.c
  rcl/src/rcl/init_options.c
  rcl/src/rcl/init_options_impl.h
  rcl/src/rcl/node.c
  rcl/src/rcl/publisher.c
  rcl/src/rcl/rcl.c
  rcl/src/rcl/rmw_implementation_identifier_check.c
  rcl/src/rcl/service.c
  rcl/src/rcl/subscription.c
  rcl/src/rcl/timer.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/arg_macros.hpp
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_client.cpp
  rcl/test/rcl/test_count_matched.cpp
  rcl/test/rcl/test_get_node_names.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_guard_condition.cpp
  rcl/test/rcl/test_init.cpp
  rcl/test/rcl/test_node.cpp
  rcl/test/rcl/test_publisher.cpp
  rcl/test/rcl/test_remap_integration.cpp
  rcl/test/rcl/test_rmw_impl_id_check_exe.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl/test/rcl/test_timer.cpp
  rcl/test/rcl/test_wait.cpp
  rcl/test/test_namespace.cpp
  rcl_action/CMakeLists.txt
  rcl_action/package.xml
  rcl_action/test/rcl_action/test_action_client.cpp
  rcl_action/test/rcl_action/test_action_communication.cpp
  rcl_action/test/rcl_action/test_action_server.cpp
  rcl_lifecycle/CMakeLists.txt
  rcl_lifecycle/package.xml
  rcl_lifecycle/test/test_default_state_machine.cpp
  rcl_lifecycle/test/test_multiple_instances.cpp
Labels: enhancement, in review

#345 fix compiler warning in clang
  rcl/src/rcl/guard_condition.c
  rcl/src/rcl/node.c
Labels: enhancement, in review

#344 Fix action tests failing in CI
  rcl_action/test/rcl_action/test_action_communication.cpp
Labels: in progress
