Repository ros2/rcl, pull requests merged in 2018-10, with the labels that each got.

#303 Add macro semicolons
  rcl/src/rcl/client.c
  rcl/src/rcl/node.c
  rcl/src/rcl/publisher.c
  rcl/src/rcl/rcl.c
  rcl/src/rcl/rmw_implementation_identifier_check.c
  rcl/src/rcl/service.c
  rcl/src/rcl/stdatomic_helper/win32/stdatomic.h
  rcl/src/rcl/subscription.c
  rcl/src/rcl/timer.c
  rcl/src/rcl/wait.c
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_wait.cpp
  rcl_lifecycle/src/com_interface.c
  rcl_lifecycle/src/rcl_lifecycle.c
  rcl_lifecycle/test/test_default_state_machine.cpp
Labels: in review

#305 Minor doc fixes
  rcl/include/rcl/client.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/rcl.h
  rcl/include/rcl/service.h
  rcl/include/rcl/wait.h
Labels: documentation

#298 Lifecycle refactor
  rcl_lifecycle/include/rcl_lifecycle/data_types.h
  rcl_lifecycle/include/rcl_lifecycle/default_state_machine.h
  rcl_lifecycle/include/rcl_lifecycle/rcl_lifecycle.h
  rcl_lifecycle/include/rcl_lifecycle/transition_map.h
  rcl_lifecycle/src/com_interface.c
  rcl_lifecycle/src/com_interface.h
  rcl_lifecycle/src/default_state_machine.c
  rcl_lifecycle/src/rcl_lifecycle.c
  rcl_lifecycle/src/states.h
  rcl_lifecycle/src/transition_map.c
  rcl_lifecycle/test/test_default_state_machine.cpp
  rcl_lifecycle/test/test_multiple_instances.cpp
  rcl_lifecycle/test/test_transition_map.cpp
Labels: in progress

#307 Add rcl_action package and headers
  rcl_action/CMakeLists.txt
  rcl_action/Doxyfile
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/default_qos.h
  rcl_action/include/rcl_action/goal_handle.h
  rcl_action/include/rcl_action/goal_state_machine.h
  rcl_action/include/rcl_action/rcl_action.h
  rcl_action/include/rcl_action/types.h
  rcl_action/include/rcl_action/wait.h
  rcl_action/package.xml
  rcl_action/src/test_compile_headers.c
Labels: in review

#315 [rcl_action] Add missing visibilty control definitions
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/goal_handle.h
  rcl_action/include/rcl_action/goal_state_machine.h
  rcl_action/include/rcl_action/types.h
  rcl_action/include/rcl_action/visibility_control.h
  rcl_action/include/rcl_action/wait.h
Labels: in review

#311 Action goal state machine tests
  rcl_action/CMakeLists.txt
  rcl_action/include/rcl_action/goal_state_machine.h
  rcl_action/include/rcl_action/types.h
  rcl_action/package.xml
  rcl_action/src/rcl_action/goal_state_machine.c
  rcl_action/test/rcl_action/test_goal_state_machine.cpp
Labels: in review

#312 [rcl_action] Implement init/fini functions for types
  rcl_action/CMakeLists.txt
  rcl_action/include/rcl_action/types.h
  rcl_action/src/rcl_action/types.c
  rcl_action/test/rcl_action/test_types.cpp
Labels: in review
