Repository ros2/rcl, pull requests merged in 2019-04, with the labels that each got.

#406 Add function to get publisher actual qos settings
  rcl/include/rcl/publisher.h
  rcl/src/rcl/publisher.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_get_actual_qos.cpp
Labels: in progress

#412 use pedantic
  rcl/CMakeLists.txt
  rcl/src/rcl/node.c
  rcl/src/rcl/security_directory.c
Labels: in review

#413 fix missing include for std::runtime_error
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
Labels: bug, in review

#404 Add more test cases for graph API + fix bug
  rcl/src/rcl/graph.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_graph.cpp
Labels: in review

#415 Correct bool reading from yaml files
  rcl_yaml_param_parser/src/parser.c
Labels: in review

#411 Add Action graph API
  rcl_action/CMakeLists.txt
  rcl_action/include/rcl_action/graph.h
  rcl_action/include/rcl_action/rcl_action.h
  rcl_action/src/rcl_action/graph.c
  rcl_action/test/rcl_action/test_graph.cpp
Labels: in review

#416 Update to be compatible with new rmw_qos_profile_t
  rcl/test/rcl/test_get_actual_qos.cpp
  rcl_action/include/rcl_action/default_qos.h
Labels: in progress

#409 Rename action state transitions
  rcl_action/include/rcl_action/types.h
  rcl_action/src/rcl_action/goal_handle.c
  rcl_action/src/rcl_action/goal_state_machine.c
  rcl_action/test/rcl_action/test_action_server.cpp
  rcl_action/test/rcl_action/test_goal_handle.cpp
  rcl_action/test/rcl_action/test_goal_state_machine.cpp
Labels: in review

#418 fix leak in __wait_set_clean_up
  rcl/src/rcl/wait.c
Labels: bug, in review

#410 Replace reinterperet_cast with static_cast
  rcl/test/rcl/test_init.cpp
  rcl/test/rcl/test_time.cpp
Labels: in progress

#426 Make sure to initialize the bool field.
  rcl/test/rcl/test_service.cpp
Labels: in review

#421 Fix argument passed to logging macros
  rcl/src/rcl/init.c
  rcl/test/rcl/test_graph.cpp
Labels: in review

#405 Migrate launch tests to new launch_testing features & API
  rcl/package.xml
  rcl/test/CMakeLists.txt
  rcl/test/cmake/rcl_add_custom_launch_test.cmake
  rcl/test/rcl/test_rmw_impl_id_check.py.in
  rcl/test/rcl/test_two_executables.py.in
Labels: in review
