Repository ros2/rcl, pull requests merged in 2019-01, with the labels that each got.

#365 Ensure that context instance id storage is aligned correctly
  rcl/include/rcl/context.h
Labels: in review

#367 Guard against bad allocation calling rcl_arguments_copy()
  rcl/src/rcl/arguments.c
  rcl/test/rcl/test_arguments.cpp
Labels: in review

#371 Add parentheses around use of zerouuid macro
  rcl_action/include/rcl_action/types.h
Labels: bug, in review

#372 add method for accessing rmw_context from rcl_context
  rcl/include/rcl/context.h
  rcl/src/rcl/context.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_context.cpp
Labels: in review

#350 Publish logs to Rosout
  rcl/CMakeLists.txt
  rcl/include/rcl/logging.h
  rcl/include/rcl/logging_rosout.h
  rcl/package.xml
  rcl/src/rcl/init.c
  rcl/src/rcl/logging.c
  rcl/src/rcl/logging_rosout.c
  rcl/src/rcl/node.c
  rcl/test/rcl/test_graph.cpp
Labels: in review

#373 pass context to wait set, and fini rmw context
  rcl/include/rcl/wait.h
  rcl/src/rcl/context.c
  rcl/src/rcl/init.c
  rcl/src/rcl/wait.c
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_count_matched.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl/test/rcl/test_timer.cpp
  rcl/test/rcl/test_wait.cpp
  rcl_action/test/rcl_action/test_action_communication.cpp
  rcl_action/test/rcl_action/test_action_interaction.cpp
Labels: in review

#368 Remove hack from unit test
  rcl/test/rcl/test_graph.cpp
Labels: in review

#376 Minor documentation typo
  rcl/include/rcl/arguments.h
Labels: in progress
