Repository ros2/rcl, pull requests merged in 2019-09, with the labels that each got.

#499 Add node name and namespace validation to graph functions
  rcl/include/rcl/graph.h
  rcl/src/rcl/graph.c
  rcl/test/rcl/test_graph.cpp
Labels: in review

#492 Add specific return code for non existent node
  rcl/include/rcl/graph.h
  rcl/include/rcl/types.h
  rcl/src/rcl/common.c
  rcl/test/rcl/test_graph.cpp
Labels: in review

#501 reset error message before setting a new one, embed the original one
  rcl_lifecycle/src/rcl_lifecycle.c
Labels: bug, in review

#504 Fix rcl_action test_graph
  rcl_action/test/rcl_action/test_graph.cpp
Labels: in review

#502 Delete rcl_impl_getenv, replaced by rcutils_get_env
  rcl/src/rcl/common.c
  rcl/src/rcl/node.c
  rcl/src/rcl/rmw_implementation_identifier_check.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_common.cpp
Labels: enhancement, in review
