Repository ros2/rcl, pull requests merged in 2019-10, with the labels that each got.

#513 add mechanism to pass rmw impl specific payloads during pub/sub creation
  rcl/include/rcl/publisher.h
  rcl/include/rcl/subscription.h
  rcl/src/rcl/publisher.c
  rcl/src/rcl/subscription.c
  rcl_action/src/rcl_action/action_client.c
Labels: enhancement

#516 Remove vestigial references to rcl_ok()
  rcl/test/rcl/test_init.cpp
Labels: needs review

#519 [rcl_action] Correct action server documentation
  rcl_action/include/rcl_action/action_server.h
Labels: in review

#517 Update rcl_node_init docstring
  rcl/include/rcl/node.h
Labels: needs review

#518 Handle zero non-ROS specific args properly in rcl_remove_ros_arguments
  rcl/src/rcl/arguments.c
  rcl/test/rcl/test_arguments.cpp
Labels: in review

#514 Not creating rosout publisher instance unless required.
  rcl/include/rcl/logging.h
  rcl/src/rcl/logging.c
  rcl/src/rcl/node.c
Labels: in review

#506 Zero copy api
  rcl/include/rcl/publisher.h
  rcl/include/rcl/subscription.h
  rcl/src/rcl/publisher.c
  rcl/src/rcl/subscription.c
Labels: enhancement

#520 Add localhost option to node creation
  rcl/CMakeLists.txt
  rcl/include/rcl/localhost.h
  rcl/src/rcl/localhost.c
  rcl/src/rcl/node.c
Labels: enhancement
