Repository ros2/rcl, pull requests merged in 2019-05, with the labels that each got.

#427 Use new test interface definitions
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_client.cpp
  rcl/test/rcl/test_count_matched.cpp
  rcl/test/rcl/test_get_actual_qos.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_publisher.cpp
  rcl/test/rcl/test_remap_integration.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl/test/test_namespace.cpp
Labels: in review

#428 Rmw preallocate
  rcl/include/rcl/publisher.h
  rcl/include/rcl/subscription.h
  rcl/src/rcl/logging_rosout.c
  rcl/src/rcl/publisher.c
  rcl/src/rcl/subscription.c
  rcl/test/rcl/test_publisher.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl_action/src/rcl_action/action_client.c
  rcl_action/src/rcl_action/action_server.c
  rcl_lifecycle/src/com_interface.c
Labels: in progress

#423 fix heap buffer overflow in test_security_directory
  rcl/test/rcl/test_security_directory.cpp
Labels: in review

#422 Add return code to CancelGoal service response
  rcl_action/src/rcl_action/action_server.c
  rcl_action/src/rcl_action/types.c
  rcl_action/test/rcl_action/test_action_server.cpp
  rcl_action/test/rcl_action/test_types.cpp
Labels: in review

#430 Add an allocator to the external logging initialization.
  rcl/include/rcl/logging_external_interface.h
  rcl/src/rcl/logging.c
Labels: in review

#408 New interfaces and their implementations for QoS features
  rcl/CMakeLists.txt
  rcl/include/rcl/event.h
  rcl/include/rcl/node.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/types.h
  rcl/include/rcl/wait.h
  rcl/src/rcl/event.c
  rcl/src/rcl/node.c
  rcl/src/rcl/publisher.c
  rcl/src/rcl/publisher_impl.h
  rcl/src/rcl/subscription.c
  rcl/src/rcl/subscription_impl.h
  rcl/src/rcl/wait.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
  rcl/test/rcl/test_count_matched.cpp
  rcl/test/rcl/test_events.cpp
  rcl/test/rcl/test_get_actual_qos.cpp
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_subscription.cpp
  rcl/test/rcl/test_timer.cpp
  rcl/test/rcl/test_wait.cpp
  rcl_action/test/rcl_action/test_action_communication.cpp
  rcl_action/test/rcl_action/test_action_interaction.cpp
Labels: in review

#432 Add new RCL_RET_UNSUPPORTED (for QoS)
  rcl/include/rcl/types.h
  rcl/src/rcl/common.c
Labels: in review

#424 fix leak in node.c
  rcl/include/rcl/security_directory.h
  rcl/src/rcl/node.c
  rcl/src/rcl/security_directory.c
Labels: in progress

#425 Changes the default 3rd party logger from rcl_logging_noop to rcl_logging_log4cxx
  rcl/cmake/get_default_rcl_logging_implementation.cmake
Labels: in review

#407 Update graph test for change to rmw names and types struct
  rcl_action/CMakeLists.txt
  rcl_action/test/rcl_action/test_graph.cpp
Labels: in review

#434 Fix leak in rcl context fini
  rcl/src/rcl/context.c
Labels: in progress

#435 add explicit dependency on rcl_logging_log4cxx
  rcl/package.xml
Labels: bug, in review

#420 fix memory leaks in test_security_directory
  rcl/src/rcl/security_directory.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_security_directory.cpp
Labels: in progress

#436 Revert "Changes the default 3rd party logger from rcl_logging_noop to…
  rcl/cmake/get_default_rcl_logging_implementation.cmake
  rcl/package.xml
Labels: in review

#437 Correct launch_testing.assert.assertExitCodes usage
  rcl/test/rcl/test_two_executables.py.in
Labels: in review

#438 Enable deadline tests for FastRTPS
  rcl/test/rcl/test_events.cpp
Labels: in progress

#433 QoS - Enable test_events unit test on macOS
  rcl/test/CMakeLists.txt
Labels: in progress

#440 fix leak in test_init
  rcl/test/rcl/test_init.cpp
Labels: in progress

#441 fix leak in test_context
  rcl/test/rcl/test_context.cpp
Labels: in progress

#439 Fix leaks in test_wait.cpp
  rcl/test/rcl/test_wait.cpp
Labels: in progress
