Repository ros2/rcl, pull requests merged in 2020-08, with the labels that each got.

#733 restore env variables set in the test_failing_configuration.
  rcl/test/rcl/test_rmw_impl_id_check_func.cpp
Labels: bug, in review

#738 Add missing calls to rcl_convert_rmw_ret_to_rcl_ret
  rcl/src/rcl/publisher.c
  rcl/src/rcl/subscription.c
Labels: enhancement

#737 Add deallocate calls to free strdup allocated memory
  rcl/src/rcl/rmw_implementation_identifier_check.c
Labels: enhancement

#745 increase timeouts in test_services fixtures for Connext
  rcl/test/rcl/client_fixture.cpp
  rcl/test/rcl/service_fixture.cpp
Labels: bug

#743 Fix bug error handling get_param_files
  rcl/src/rcl/arguments.c
  rcl/test/rcl/allocator_testing_utils.h
  rcl/test/rcl/test_arguments.cpp
Labels: bug

#748 Fix allocation arguments copy
  rcl/src/rcl/arguments.c
  rcl/test/rcl/test_arguments.cpp
Labels: bug

#770 Fix wait allocation cleanup
  rcl/src/rcl/wait.c
Labels: bug, enhancement
