Repository ros2/rcl, pull requests merged in 2020-03, with the labels that each got.

#578 Document clock types
  rcl/include/rcl/time.h
Labels: enhancement

#575 [rcl lifecycle] removed rmw_implementation from package.xml
  rcl_lifecycle/CMakeLists.txt
  rcl_lifecycle/package.xml
Labels: enhancement

#587 Use 10sec lifespan in rosout publisher qos
  rcl/src/rcl/logging_rosout.c
Labels: in review

#589 Trigger guard condition when timer is reset
  rcl/src/rcl/timer.c
  rcl/src/rcl/wait.c
Labels: bug, in review

#601 Add missing node destruction
  rcl/test/rcl/test_get_node_names.cpp
Labels: bug, in review

#535 Support for ON_REQUESTED_INCOMPATIBLE_QOS and ON_OFFERED_INCOMPATIBLE_QOS events
  rcl/include/rcl/event.h
  rcl/src/rcl/event.c
  rcl/test/rcl/test_events.cpp
Labels: in review
