Repository ros2/rcl, pull requests merged in 2020-04, with the labels that each got.

#597 Change naming style for private functions
  rcl/src/rcl/time.c
Labels: enhancement

#608 remove tinydir_vendor dependency
  rcl/CMakeLists.txt
  rcl/package.xml
Labels: in review

#607 Use keystore root as security root directory, and not contexts folder
  rcl/src/rcl/security.c
  rcl/test/rcl/test_security.cpp
  rcl/test/resources/test_security_directory/contexts/dummy_security_context/.gitkeep
  rcl/test/resources/test_security_directory/contexts/group1/dummy_security_context/.gitkeep
Labels: in review

#603 Remove deprecated CLI rules
  rcl/include/rcl/arguments.h
  rcl/src/rcl/arguments.c
  rcl/test/rcl/test_arguments.cpp
Labels: enhancement, in review

#609 Fix security directory lookup for '/' security contexts
  rcl/src/rcl/security.c
  rcl/test/rcl/test_security.cpp
Labels: bug, in review

#626 Fixed argument name in rcl_lifecycle.h
  rcl_lifecycle/include/rcl_lifecycle/transition_map.h
Labels: enhancement, ready

#579 Don't call `rcl_logging_configure/rcl_logging_fini` in `rcl_init/rcl_shutdown`
  rcl/include/rcl/init_options.h
  rcl/src/rcl/init.c
  rcl/src/rcl/init_options.c
  rcl/test/rcl/test_graph.cpp
  rcl/test/rcl/test_logging_rosout.cpp
Labels: in review

#619 Message info with timestamps support in rcl
  rcl/src/rcl/subscription.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_subscription.cpp
Labels: enhancement

#622 Added documentation to rcl_lifecycle
  rcl_lifecycle/include/rcl_lifecycle/default_state_machine.h
  rcl_lifecycle/include/rcl_lifecycle/rcl_lifecycle.h
  rcl_lifecycle/include/rcl_lifecycle/transition_map.h
Labels: documentation, ready

#637 Fixed rcl_yaml_param_parser package description
  rcl_yaml_param_parser/package.xml
Labels: documentation, enhancement

#634 added rcl yaml param parser doxyfile
  rcl_yaml_param_parser/Doxyfile
Labels: enhancement

#633 Added rcl_lifecycle Doxyfile
  rcl_lifecycle/Doxyfile
Labels: documentation, enhancement
