Repository ros2/rcl, pull requests merged in 2020-02, with the labels that each got.

#576 Update rmw_topic_endpoint_info_array usage
  rcl/test/rcl/test_info_by_topic.cpp
Labels: in review

#562 Fix memory leak in test_subscription_nominal (#469)
  rcl/test/rcl/test_subscription.cpp
Labels: bug

#577 [rcl_action] changed build_depend and build_depend_export dependencies to depend
  rcl_action/package.xml
Labels: enhancement

#582 make rosout publisher transient local with a depth of 1000
  rcl/src/rcl/logging_rosout.c
Labels: bug
