Repository ros2/rcl, pull requests merged in 2020-06, with the labels that each got.

#670 Fix conversions between rmw_localhost_only_t and bool
  rcl/src/rcl/localhost.c
  rcl/src/rcl/node.c
Labels: bug, in review

#672 print RCL_LOCALHOST_ENV_VAR if error happens via rcutils_get_env.
  rcl/src/rcl/localhost.c
Labels: in review

#675 [Foxy] print RCL_LOCALHOST_ENV_VAR if error happens via rcutils_get_env. (#672)
  rcl/src/rcl/localhost.c
Labels: in review

#668 Add tests for rcl package
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_client.cpp
  rcl/test/rcl/test_common.cpp
  rcl/test/rcl/test_domain_id.cpp
  rcl/test/rcl/test_localhost.cpp
  rcl/test/rcl/test_node.cpp
  rcl/test/rcl/test_service.cpp
  rcl/test/rcl/test_wait.cpp
Labels: in review

#673 Add message lost event
  rcl/include/rcl/event.h
  rcl/src/rcl/event.c
Labels: enhancement, in review

#671 Add check rcl_node_options_copy invalid out
  rcl/src/rcl/node_options.c
  rcl/test/rcl/test_node.cpp
Labels: enhancement, in review

#701 [backport Dashing] Added rcl yaml param parser doxyfile (#634)
  rcl_yaml_param_parser/Doxyfile
Labels: documentation

#700 [backport Eloquent] Added rcl yaml param parser doxyfile (#634)
  rcl_yaml_param_parser/Doxyfile
Labels: documentation

#674 Update quality declaration and coverage
  rcl/QUALITY_DECLARATION.md
  rcl/README.md
  rcl_action/QUALITY_DECLARATION.md
  rcl_action/README.md
  rcl_lifecycle/QUALITY_DECLARATION.md
  rcl_lifecycle/README.md
  rcl_yaml_param_parser/QUALITY_DECLARATION.md
  rcl_yaml_param_parser/README.md
Labels: enhancement
