Repository ros2/rcl, pull requests merged in 2020-05, with the labels that each got.

#644 Included features
  README.md
  rcl/README.md
  rcl_action/README.md
  rcl_lifecycle/README.md
  rcl_yaml_param_parser/README.md
  rcl_yaml_param_parser/include/rcl_yaml_param_parser/parser.h
Labels: documentation

#640 Make test_two_timers_ready_before_timeout more reliable
  rcl/test/rcl/test_timer.cpp
Labels: bug, in review

#645 Remove MANUAL_BY_NODE liveliness API
  rcl/include/rcl/node.h
  rcl/src/rcl/node.c
  rcl/test/rcl/test_events.cpp
Labels: in review

#652 warn about unused return value for set_logger_level
  rcl/include/rcl/logging_external_interface.h
  rcl/include/rcl/macros.h
  rcl/src/rcl/logging.c
Labels: bug

#658 Remove _rcl_parse_bool_arg and _atob
  rcl/src/rcl/arguments.c
Labels: in review

#660 Expose rcl default logging output handler
  rcl/include/rcl/logging.h
  rcl/src/rcl/logging.c
Labels: in review

#659 Improved rcl docblock
  rcl/include/rcl/context.h
  rcl/include/rcl/event.h
  rcl/include/rcl/graph.h
  rcl/include/rcl/init.h
  rcl/include/rcl/logging.h
  rcl/include/rcl/logging_rosout.h
  rcl/include/rcl/node.h
  rcl/include/rcl/node_options.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/security.h
  rcl/include/rcl/service.h
  rcl/include/rcl/subscription.h
  rcl/include/rcl/time.h
  rcl/include/rcl/timer.h
  rcl/include/rcl/validate_enclave_name.h
  rcl/include/rcl/wait.h
Labels: documentation, enhancement
