Repository ros2/rcl, pull requests merged in 2020-07, with the labels that each got.

#708 Remove domain_id and localhost_only from node_options
  rcl/include/rcl/context.h
  rcl/include/rcl/init_options.h
  rcl/include/rcl/node_options.h
  rcl/src/rcl/context.c
  rcl/src/rcl/init_options.c
  rcl/src/rcl/node.c
  rcl/src/rcl/node_options.c
  rcl/test/rcl/test_node.cpp
Labels: enhancement

#664 Implement a generic way to change logging levels
  rcl/CMakeLists.txt
  rcl/include/rcl/arguments.h
  rcl/include/rcl/log_level.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/arguments_impl.h
  rcl/src/rcl/log_level.c
  rcl/src/rcl/logging.c
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_log_level.cpp
Labels: enhancement

#702 [Backport Dashing] Fixed doxygen warnings (#677)
  rcl/include/rcl/event.h
  rcl/include/rcl/graph.h
  rcl/include/rcl/logging_rosout.h
  rcl/include/rcl/node_options.h
  rcl/include/rcl/remap.h
  rcl/include/rcl/validate_topic_name.h
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/wait.h
Labels: documentation

#719 [foxy] Set domain id to 0 if it is RMW_DEFAULT_DOMAIN_ID
  rcl/src/rcl/init.c
  rcl/src/rcl/node.c
Labels: bug, in review

#712 Removed doxygen warnings
  rcl/Doxyfile
  rcl/include/rcl/client.h
  rcl/include/rcl/event.h
  rcl/include/rcl/guard_condition.h
  rcl/include/rcl/lexer_lookahead.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/service.h
  rcl/include/rcl/subscription.h
  rcl/include/rcl/time.h
  rcl/include/rcl/wait.h
  rcl_action/Doxyfile
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/goal_handle.h
  rcl_action/include/rcl_action/types.h
  rcl_lifecycle/Doxyfile
  rcl_lifecycle/include/rcl_lifecycle/data_types.h
  rcl_yaml_param_parser/Doxyfile
  rcl_yaml_param_parser/include/rcl_yaml_param_parser/parser.h
  rcl_yaml_param_parser/include/rcl_yaml_param_parser/types.h
Labels: documentation

#718 Move actual domain id from node to context
  rcl/include/rcl/context.h
  rcl/src/rcl/context.c
  rcl/src/rcl/node.c
  rcl/test/rcl/test_context.cpp
  rcl/test/rcl/test_node.cpp
Labels: bug, in review

#724 [Backport foxy] Removed doxygen warnings (#712)
  rcl/Doxyfile
  rcl/include/rcl/client.h
  rcl/include/rcl/event.h
  rcl/include/rcl/guard_condition.h
  rcl/include/rcl/lexer_lookahead.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/service.h
  rcl/include/rcl/subscription.h
  rcl/include/rcl/time.h
  rcl/include/rcl/wait.h
  rcl_action/Doxyfile
  rcl_action/include/rcl_action/action_client.h
  rcl_action/include/rcl_action/action_server.h
  rcl_action/include/rcl_action/goal_handle.h
  rcl_action/include/rcl_action/types.h
  rcl_lifecycle/Doxyfile
  rcl_lifecycle/include/rcl_lifecycle/data_types.h
  rcl_yaml_param_parser/Doxyfile
  rcl_yaml_param_parser/include/rcl_yaml_param_parser/parser.h
  rcl_yaml_param_parser/include/rcl_yaml_param_parser/types.h
Labels: documentation

#720 Add function rcl_event_is_valid
  rcl/include/rcl/event.h
  rcl/src/rcl/event.c
  rcl/src/rcl/event_impl.h
  rcl/test/CMakeLists.txt
  rcl/test/rcl/test_events.cpp
Labels: enhancement

#726 Add extra check for invalid event implementation
  rcl/src/rcl/event.c
  rcl/test/rcl/test_events.cpp
Labels: enhancement
