Repository ros2/rcl, pull requests merged in 2021-09, with the labels that each got.

#931 fix expired goals capacity of action server
  rcl_action/src/rcl_action/action_server.c
Labels: bug

#932 Fix up documentation build for rcl when using rosdoc2
  rcl/Doxyfile
  rcl/include/rcl/arguments.h
  rcl/include/rcl/client.h
  rcl/include/rcl/context.h
  rcl/include/rcl/event.h
  rcl/include/rcl/guard_condition.h
  rcl/include/rcl/init_options.h
  rcl/include/rcl/lexer.h
  rcl/include/rcl/lexer_lookahead.h
  rcl/include/rcl/log_level.h
  rcl/include/rcl/node.h
  rcl/include/rcl/node_options.h
  rcl/include/rcl/publisher.h
  rcl/include/rcl/remap.h
  rcl/include/rcl/service.h
  rcl/include/rcl/subscription.h
  rcl/include/rcl/time.h
  rcl/include/rcl/timer.h
  rcl/include/rcl/wait.h
  rcl/src/rcl/arguments.c
  rcl/src/rcl/arguments_impl.h
  rcl/src/rcl/client.c
  rcl/src/rcl/context_impl.h
  rcl/src/rcl/event_impl.h
  rcl/src/rcl/guard_condition.c
  rcl/src/rcl/init_options_impl.h
  rcl/src/rcl/lexer.c
  rcl/src/rcl/lexer_lookahead.c
  rcl/src/rcl/node.c
  rcl/src/rcl/publisher_impl.h
  rcl/src/rcl/remap_impl.h
  rcl/src/rcl/service.c
  rcl/src/rcl/subscription_impl.h
  rcl/src/rcl/time.c
  rcl/src/rcl/timer.c
  rcl/src/rcl/wait.c
  rcl/test/rcl/test_lexer_lookahead.cpp
  rcl/test/rcl/test_time.cpp
Labels: documentation

#935 test should check specified number of entities.
  rcl/src/rcl/graph.c
  rcl/test/rcl/test_graph.cpp
Labels: enhancement, tests
